nome = input('Digite o seu nome: ')
nota1 = float(input('Digite a sua primeira nota: '))
nota2 = float(input('Digite a sua segunda nota: '))
nota3 = float(input('Digite a sua terceira nota: '))
print(f'O aluno {nome} teve média de {(nota1+nota2+nota3)/3}')